name: Geth-Lite Release Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: true # Force a clean checkout to avoid cache issues
          fetch-depth: 0 # Ensure entire history is fetched

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Get current tag version
        id: get_current_tag
        run: echo "::set-output name=tag_version::${{ vars.TAG_VERSION }}"

      - name: Increment tag
        id: increment_tag
        run: |
          current_tag=${{ steps.get_current_tag.outputs.tag_version }}
          if [[ -z $current_tag ]]; then
            next_tag="v0.0.1"  # Base case for initial tag
          else
            current_tag="${current_tag/v/}"  # Remove 'v'
            IFS='.' read -r major minor patch <<< "$current_tag"
            if [ "$patch" == "9" ]; then
              next_tag="v$major.$minor.$((patch + 1))"  # Increment minor
            else
              next_tag="v$major.$minor.$((patch + 1))"  # Increment patch
            fi
          fi
          echo "::set-output name=next_tag::$next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Set environment variable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "MY_ENV_VARIABLE=new_value" >> $GITHUB_ENV

      - name: Update tag version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "TAG_VERSION=${{steps.increment_tag.outputs.next_tag }}" >> $GITHUB_STATE

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.increment_tag.outputs.next_tag}}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
