name: Geth-Lite Release Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: true # Force a clean checkout to avoid cache issues
          fetch-depth: 0 # Ensure entire history is fetched

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
     GITHUB_TOKEN: ${{ github.token }}
    steps:


      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
    

      - name: Initialize git repository
        run: git init
      - name: Get last tag
        id: get_tag
        run: 
          echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo previoustag

      - name: Print last tag
        run: echo "Last tag is ${{ steps.get_tag.outputs.tag }}"

      - name: Get current tag version
        id: get_current_tag
        run: 

          latest_tag=$(git describe --tags --exact-match 2>/dev/null || echo "")
           echo "tag_version=$latest_tag" >> $GITHUB_OUTPUT  

      - name: Increment tag
        id: increment_tag
        run: |
          current_tag=${{ steps.get_current_tag.outputs.tag_version }}
          if [[ -z $current_tag ]]; then
            next_tag="v0.0.1"  # Base case for initial tag
          else
            current_tag="${current_tag/v/}"  # Remove 'v'
            IFS='.' read -r major minor patch <<< "$current_tag"
            if [ "$patch" == "9" ]; then
              next_tag="v$major.$minor.$((patch + 1))"  # Increment minor
            else
              next_tag="v$major.$minor.$((patch + 1))"  # Increment patch
            fi
          fi
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
       
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
        
          tag_name: ${{ steps.increment_tag.outputs.next_tag}}
          release_name: Release ${{ steps.increment_tag.outputs.next_tag}}
          draft: false
          prerelease: false
               
